export const CLEAN_SINGLE_TASK = "CLEAN_SINGLE_TASK";
export const ADD_SINGLE_TASK = "ADD_SINGLE_TASK";
export const DELETE_SINGLE_TASK = "DELETE_SINGLE_TASK";
export const SET_PIN_TASK = "SET_PIN_TASK";
export const DISABLE_PIN_TASK = "DISABLE_PIN_TASK";
export const REMOVE_PIN_TASK = "REMOVE_PIN_TASK";
export const UPDATE_SINGLE_TASK = "UPDATE_SINGLE_TASK";
